name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "235bd42749d9d4f3294549a4d7acc8ef1e0ecba180dc1cf72b3af5a50367b136"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
