name = "Craftocracy"
author = "gelvetica, Craftocracy, and the Strudel General Assembly"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a66c9da6a8f650f0326d536181604ddad4f5d1a7042cc7ade1bee5b0f692e807"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
