name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0850057d5f473ad27a0e098a57bd47b83eb79d5fe1e5bf2b0f8d001fe3b4768b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
