name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd36e4cd37fcde9615ff1c97ce37d43116be4679ed67a0ae9f4be7caceb8c4cc"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
