name = "Craftocracy"
author = "gelvetica, Craftocracy, and the Strudel General Assembly"
version = "2.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e556a5918ad6ccaa21cd2f8423b7425af45d3eb0c0630d13285b2f41ae9d1854"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
