name = "Craftocracy"
author = "gelvetica, Craftocracy, and the Strudel General Assembly"
version = "2.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ead324ea6a7c089f340b1075305df436e6c45785c262522bf914f542d229024"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
