name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9518f2465025118f77c665a32694bec30747360264185c923cd33c803885c7b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
