name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1a5cff73783e6751782e6f07bd85b63d56b81997d436a33b14f3cfd6c085944"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
