name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37642fa80bd1f53da583262a19faf9c27797c8c2a71a3f7f3fc92a297184eac0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
