name = "Craftocracy"
author = "gelvetica, Craftocracy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24e66005837efb9e4a9014d86a7bcd92fbf8d87115d743cbf8238370f9e674bd"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
